### ISSUE TITLE
Question : Vision of the project

### ISSUE THREAD

**Issue by warmachinesocial** [NOXCIS/wirehole#25]
Hi just wanna ask if project is focused towards vpn and dns queries been cached or are is there aim towards something more like casaos?

Just a quick question I don't know if you have heard of netbird but I recently found out on libhunt about it. Would you wanna integrate it or like just use simple wireguard + wg-dashboard.

Any plans on making docker image for providing updates?

**Comment by warmachinesocial** [comment]
Could we have headscale here? to replace wg-dashboard?

**Comment by NOXCIS** [comment]
- Worm-Hole is designed to facilitate privacy and security above all else. It's like netbird its but is able to be deployed anonymously and it's free. Think of it as a **framework** to do something like casaos or netbird. 

- Theres already auto daily builds on the latest tag: orca

- Headscale, No I don't have time to modify and build an image of Headscale that works with the installer, at the moment. Maybe in the future. However I must emphasize the need for a dashboard with a simple code base and few breaking deps.
